# Generated by Django 3.1 on 2020-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithm', '0002_auto_20200808_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_title_no',
            field=models.IntegerField(default=0),
        ),
    ]
