# Generated by Django 3.1 on 2020-08-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptitle',
            name='title_no',
            field=models.IntegerField(default=1),
        ),
    ]
