# Generated by Django 3.1 on 2020-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200805_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title_no',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
