# Generated by Django 3.1 on 2020-08-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_sub_title_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title_no',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
