# Generated by Django 3.1 on 2020-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200805_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_no',
            field=models.IntegerField(default=0),
        ),
    ]
