# Generated by Django 3.1 on 2020-08-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200805_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title_no',
            field=models.FloatField(),
        ),
    ]
