# Generated by Django 3.1 on 2020-08-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200806_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_items',
            name='t_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nav_items',
            name='tab_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
