# Generated by Django 3.1 on 2020-08-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200806_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_Name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Nav_Items',
        ),
    ]
