# Generated by Django 3.1 on 2020-08-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200806_0207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groupTitle',
            new_name='GROUP_TITLE',
        ),
    ]
