# Generated by Django 3.1 on 2020-08-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200806_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_item',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
